apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ACR-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ACR-app
  template:
    metadata:
      labels:
        app: ACR-app
    spec:
      containers:
      - name: my-ACR-app
        image: acrregistry12.azurecr.io/my-ACR-app:$BUILD_NUMBER
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: ACR-app-service
spec:
  selector:
    app: ACR-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
