apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ACR-deployment
  labels:
    app: ACR-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ACR-app
  template:
    metadata:
      labels:
        app: ACR-app
    spec:
      containers:
        - name: my-ACR-app
          image: acrregistry12.azurecr.io/my-ACR-app:$BUILD_NUMBER
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ACR-app-service
  labels:
    app: ACR-app
spec:
  type: LoadBalancer
  selector:
    app: ACR-app
  ports:
    - port: 5000
      targetPort: 5000
